name: Package

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
        image: termux/package-builder
    strategy:
      matrix:
        target_arch: [aarch64]
    timeout-minutes: 30
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          repository: termux/termux-packages
          fetch-depth: 1000
      - name: Clone nginx-rtmp
        uses: actions/checkout@v4
        with:
          path: packages/ngx
      - name: Configure environment
        run: |
          ./scripts/setup-android-sdk.sh
      - name: Build
        env:
          TERMUX_DEBUG: false
        run: |
          ./build-package.sh -I -a ${{ matrix.target_arch }} ngx
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: debs-${{ matrix.target_arch }}
          path: output/*

